server:
  port: 7000
spring:
  application:
    name: bookconsumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: INFO
