server:
  port: 8000
spring:
  application:
    name: bookconsumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://123.57.58.105:2000/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: INFO
